# NOTE: Generated By HttpRunner v3.1.6
# FROM: har/test.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTest(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/third/wallet/accounts/v1")
            .get("https://app.yinxiang.com/third/wallet/accounts/v1")
            .with_headers(
                **{
                    "User-Agent": "YXBJ Android New/master_286.2024059 (zh_CN); Android/11; M2102J2SC/30; EDAMVersion=V2;",
                    "auth-token": "S=s31:U=1881e6e:E=1c77b6ef278:C=17e0e833960:P=1dd:A=yx-android-xauth-new:V=2:H=6e90184c3542e4eeae4db4487dd9ac09",
                    "Host": "app.yinxiang.com",
                    "Connection": "Keep-Alive",
                    "Accept-Encoding": "gzip",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", "SUCCESS")
            .assert_equal("body.message", "")
        ),
    ]


if __name__ == "__main__":
    TestCaseTest().test_start()
